name: Update API Data

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:      # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write        # Needed to push commit
      pull-requests: write   # Needed to open a PR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch API and update file
        run: |
          echo "Fetching data from API..."
          FILE_NAME=$(date +'%Y%m%d%H%M').json
          curl -s "https://uselessfacts.jsph.pl/api/v2/facts/random?language=en" > $FILE_NAME
          echo "Data saved to data.json"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update data.json from API"
          title: "Update API data"
          body: "This PR updates data.json with the latest data from the API."
          branch: update-api-data
          base: main  # or your default branch
