name: Query API and Commit Results

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour 
  workflow_dispatch: # Allows manual triggering

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Query API and save result
        run: |
          API_URL="https://uselessfacts.jsph.pl/api/v2/facts/random?language=en"
          curl -s "$API_URL" > data.json

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git checkout -b update-api-data || git checkout update-api-data
          git pull --rebase origin update-api-data || echo "Nothing to rebase"
          git add data.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update data.json with latest API results"
          git push origin update-api-data

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update data.json with latest API results"
          title: "Update API data"
          body: "Automated PR to update data.json from API."
          branch: update-api-data
