name: Update API Data

on:
  schedule:
    - cron: '0 17 * * *'  once a day at 1700
  workflow_dispatch:      # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write        # Needed to push commit
      pull-requests: write   # Needed to open a PR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python modules
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install --user numpy scipy matplotlib ipython jupyter pandas plotly requests pycountry

      - name: Fetch API and update file
        run: |
          echo "Fetching data from API..."
          DATE_STAMP=$(date +'%Y%m%d_%H%M')
          FILE_NAME="data/$DATE_STAMP.json"
          curl -s "https://uselessfacts.jsph.pl/api/v2/facts/random?language=en" > $FILE_NAME
          echo "Writing data to $FILE_NAME"
          echo "DATESTAMP=$DATE_STAMP" >> $GITHUB_ENV
          echo "FILENAME=$FILE_NAME" >> $GITHUB_ENV
          cat $FILE_NAME
      - name: Validate JSON file
        run: |
          if jq empty "${{ env.FILENAME }}"; then
             echo "✅ JSON validation passed: data successful"
          else
             echo "❌ JSON validation failed"
             exit 1
          fi
      - name: Run shell script to create index page
        run: bash get_facts.sh
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "new api call for ${{ env.DATESTAMP }}"
          title: "Update API data"
          body: "New API call"
          branch: "api-update-${{ env.DATESTAMP }}"
          base: main  # or your default branch


      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto $PULL_REQUEST_NUMBER
        env:
          GH_TOKEN: ${{ secrets.PAT }}
