name: Update API Data

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:      # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write        # Needed to push commit
      pull-requests: write   # Needed to open a PR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch API and update file
        run: |
          echo "Fetching data from API..."
          FILE_NAME=$(date +'%Y%m%d%H%M').json
          curl -s "https://uselessfacts.jsph.pl/api/v2/facts/random?language=en" > $FILE_NAME
          cat $FILE_NAME
      - name: Validate JSON file
        run: |
          if jq empty "${{ env.FILE_NAME }}"; then
             echo "✅ JSON validation passed: data successful"
          else
             echo "❌ JSON validation failed"
             exit 1
          fi
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "new api call"
          title: "Update API data"
          body: "New API call"
          branch: "api-update"
          base: main  # or your default branch
